In [1]:
import numpy as np

# Masukkan nilai input x dan bobot W1, W2, W3 dan W4
x = np.matrix([[3], [2], [-1]])

w1 = np.matrix([
    [4, 1, 2, 1],
    [2, -3, 1, -2],
    [-1, 2, 3, 1]
])

w2 = np.matrix([
    [1, 3, -2, 1],
    [3, -1, 1, 3],
    [2, 2, 3, 2],
    [4, -2, -1, 1]
])

w3 = np.matrix([
    [1, 2, -1, 2],
    [-2, 3, -3, 1],
    [4, -1, 1, 2],
    [1, 1, 3, -2]
])

w4 = np.matrix([
    [3, -2, -1],
    [-1, 2, 1],
    [-2, -3, 3],
    [1, 4, -4]
])

In [2]:
# masukkan nilai bias b1, b2, b3 dan b4
b1 = np.matrix([[-4], [2], [1], [-1]])
b2 = np.matrix([[-1],[2], [-3], [1]])
b3 = np.matrix([[2], [-3], [-1],[4]])
b4 = np.matrix([[3], [-1], [-2]])

In [3]:
w1_T = np.transpose(w1)
w2_T = np.transpose(w2)
w3_T = np.transpose(w3)
w4_T = np.transpose(w4)

In [5]:
# hitung nilai dari input ke hidden layer h_1
h_1=(w1_T*x) + b1
print(h_1)

[[13]
 [-3]
 [ 6]
 [-3]]


In [6]:
# Fungsi aktivasi yang bisa digunakan
def sigmoid(mat):
    return 1 / (1 + np.exp(-mat))

def relu(mat):
    return np.maximum(0, mat)

def tanh(mat):
    return np.tanh(mat)

def softmax(mat):
    e_z = np.exp(mat - np.max(mat))
    return e_z / e_z.sum(axis=0)

hidden layer softmax

In [8]:
# aktifkan fungsi aktivasi softmax pada h_1
h1_aktivasi = softmax(h_1)
h1_aktivasi

matrix([[9.99088724e-01],
        [1.12432624e-07],
        [9.11050990e-04],
        [1.12432624e-07]])

In [10]:
# hitung nilai pada hidden layer h_2
h_2= (w2_T*h1_aktivasi) + b2
h_2

matrix([[ 9.11613153e-04],
        [ 4.99908794e+00],
        [-4.99544430e+00],
        [ 2.00091128e+00]])

In [12]:
# aktifkan fungsi aktivasi softmax pada h_2
h2_aktivasi = softmax(h_2)
h2_aktivasi

matrix([[6.38820219e-03],
        [9.46365829e-01],
        [4.32005079e-05],
        [4.72027684e-02]])

In [13]:
# hitung nilai pada hidden layer h_2
h_3= (w3_T*h2_aktivasi) + b3
h_3

matrix([[ 0.16103211],
        [-0.10096654],
        [-3.70383418],
        [ 4.8648231 ]])

In [14]:
# aktifkan fungsi aktivasi softmax pada h_3
h3_aktivasi = softmax(h_3)
h3_aktivasi

matrix([[8.91621220e-03],
        [6.86113280e-03],
        [1.86934857e-04],
        [9.84035720e-01]])

In [17]:
# # aktifkan fungsi aktivasi Sigmoid pada output
out = (w4_T*h3_aktivasi) + b4
output = sigmoid(out)

# nilai output
print(output)

[[0.98207637]
 [0.94938046]
 [0.00263131]]
